### ISSUE TITLE
setting and reading trigger level not working

### ISSUE THREAD

**Issue by gjzamiar** [labnation/DeviceInterface#4]
//Trigger level never seems to be set or read, this code compiles and does do throw exceptions  
    private void button3_Click(object sender, EventArgs e)
        {
             //I have tried it both way running true and false            
            //scope.Running = false; 
            //scope.CommitSettings();
            if (NewTrigLev == "1V")
            {
                TriggerValue trigger = new TriggerValue() // tried this method and the method in the else
                {
                    channel = AnalogChannel.ChA,
                    edge = TriggerEdge.RISING,
                    level = 1.0f,
                   };
            }
            else if (NewTrigLev == "5V")
            {
                {
                    scope.TriggerValue.level = 5.0f;
                    
                }
            }
            scope.Running = true;
            scope.CommitSettings();
            label7.Text = "Trigger level:   " + scope.TriggerValue.level.ToString();
            label6.Text = DateTime.Now.ToString(); 
  }

**Comment by louiecaulfield** [comment]
The getter of scope.TriggerValue returns a new instance of the ```TriggerValue``` class. To update the scope's trigger value, you **must**  use the scope.TriggerValue setter. So, what should work is:

```csharp
var tv = scope.TriggerValue;
tv.level = 5.0f;
scope.TriggerValue = tv;
```

**Comment by gjzamiar** [comment]
Thanks - That worked

George
